CatsCatsCats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      post 'approve'
      post 'deny'
    end
  end
  
  resources :users, only: [:new, :create]
  resource :session, only: [:create, :new]
  delete '/session' => 'sessions#destroy', :as => 'delete_session'
end

CatsCatsCats/app/models/cat.rb
class Cat < ActiveRecord::Base
  GENDERS = ["M", "F"]
  
  validates :birth, :color, :name, :sex, :description, presence: true
  validates :sex, inclusion: GENDERS
  has_many :cat_rental_requests, :dependent => :destroy
  
  belongs_to(
    :owner,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )
  
  #validates :birth <= Time.now
  
end

CatsCatsCats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUS = ["PENDING", "APPROVED", "DENIED"]
  
  validates :cat_id, :start_date, :end_date, presence: true
  validates :user, presence: true
  validates :status, inclusion: STATUS
  validate :overlapping_approved_requests
  validate :no_time_traveling
  belongs_to :cat
  belongs_to :user
  
  def overlapping_requests?(cat1, cat2)
    (cat1.start_date <= cat2.end_date && cat1.end_date >= cat2.start_date) ||
    (cat2.start_date <= cat1.end_date && cat2.end_date >= cat1.start_date)
  end
  
  def overlapping_approved_requests
    @rental_requests = CatRentalRequest.where('status = ?', 'APPROVED')
    
    @rental_requests.each do |request|
      next if request == self
      return false if overlapping_requests?(self, request)
    end
    true
  end
  
  def no_time_traveling
    self.start_date < self.end_date
  end
  
  def approve!
    CatRentalRequest.transaction do
      self.status = "APPROVED" 
      self.save!
      
      rental_requests = CatRentalRequest.where('status = ?', 'PENDING')
      rental_requests.each do |request|
      request.deny! if overlapping_requests?(self, request)
      end
      
    end
    puts "Approved for #{self.cat}!!"
  end
  
  def deny!
    self.status = "DENIED"
    self.save!
  end
end

CatsCatsCats/app/models/user.rb
class User < ActiveRecord::Base
  before_validation(on: :create) { reset_session_token! }
  attr_reader :password
  
  validates :session_token, :user_name, :password_digest, presence: true 
  validates :password, length: { minimum: 6, allow_nil: true}
  has_many :cats
  has_many :requests
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    password_digest.is_password?(password)
  end
  
  def badger=(asdf)
    100.times{puts 'digs'}
  end
  
  def password_digest
     BCrypt::Password.new(read_attribute("password_digest")) #rails is MAGIC
  end
  
  def self.find_by_credentials(user_options = {})
    
    user = User.find_by(user_name: user_options[:user_name])
    if user && user.is_password?(user_options[:password])
      user
    end
  end
  
end

CatsCatsCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 
 def current_user
   return nil if session[:session_token].nil?
    User.find_by(session_token: session[:session_token])
 end
 
 def login_user!(user)
   user.reset_session_token!
   session[:session_token] = user.session_token
   user.save!
 end
 
 def log_out!
   self.session[:session_token] = nil
 end
 
 helper_method :current_user
end

CatsCatsCats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :owns_cat, only: [:approve, :deny]
  
  def owns_cat
    cat_id = CatRentalRequest.find(params[:id]).cat_id
    @cat = Cat.find(cat_id)
    redirect_to cats_url if @cat.user_id != current_user.id
  end
  
  def index
    @cats = Cat.all
    @requests = CatRentalRequest.all
    
  end
  
  def create
    @cats = Cat.all
    @request = CatRentalRequest.new(cat_rental_params)
    @request.user_id = current_user.id
    if @request.save
      redirect_to cat_url(@request.cat_id)
    else
      render json: @request.errors.full_messages
    end
  end
  
  def new
    @cats = Cat.all
    @request = CatRentalRequest.new
  end
  
  def show
    @request = CatRentalRequest.find(params[:id])
    render json: @request
  end
  
  def destroy
    @request = CatRentalRequest.find(params[:id])
    @request.destroy!
    render json: @request
  end
  
  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    redirect_to cat_url(@request.cat_id)
  end
  
  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    redirect_to cat_url(@request.cat_id)
  end

  protected
  
  def cat_rental_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date,
    :end_date, :status)
  end
end

CatsCatsCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :owns_cat, only: [:edit, :update]
  
  def owns_cat
    @cat = Cat.find(params[:id])
    redirect_to cats_url if @cat.user_id != current_user.id
  end
  
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @requests = CatRentalRequest.where("cat_id = ?",params[:id]).order("start_date ASC")
    @cat = Cat.find(params[:id])
    render :show
  end
  
  def create
    @cat = Cat.new(cat_params)
    @user_id = current_user.id
    @cat.user_id = @user_id
    
    if @cat.save!
      redirect_to cats_url
    else
      render :new 
    end
  end
  
  def new
    @cat = Cat.new
  end
  
  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end
  
  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cats_url
    else
      render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end
  
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy!
    render json: @cat
  end
  private
  
  def cat_params
    params.require(:cat).permit(:birth, :color, :name, :sex, :description)
  end
end

CatsCatsCats/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :to_cats, only: [:new, :create]
  
  def to_cats
    redirect_to(cats_url) if !current_user.nil?
  end
  
  def new
    @session = User.new 
    render :new
  end

  def create
    if @session = User.find_by_credentials(session_params)
      login_user!(@session)
      redirect_to cats_url
    else
      render :new
    end
  end
  
  def destroy
    @session = current_user
    session[:session_token] = nil
    @session.reset_session_token!
    redirect_to cats_url
  end
  
  private
  def session_params
    params.require(:user).permit(:user_name, :password)
  end
end

CatsCatsCats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :to_cats
  
  def to_cats
    redirect_to(cats_url) if !current_user.nil?
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)
      redirect_to cats_url
    else
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:user_name, :password, :badger)
  end
end

CatsCatsCats/app/helpers/application_helper.rb
module ApplicationHelper
end

CatsCatsCats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

CatsCatsCats/app/helpers/cats_helper.rb
module CatsHelper
end

CatsCatsCats/app/helpers/sessions_helper.rb
module SessionsHelper
end

CatsCatsCats/app/helpers/users_helper.rb
module UsersHelper
end

CatsCatsCats/app/views/cat_rental_requests/_form.html.erb
<form action="<%= cat_rental_requests_url %>" method="POST">
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <label>Cat:
    <select name="cat_rental_request[cat_id]">
      <% @cats.each do |cat| %>
      <option value="<%=cat.id%>">
        <%= cat.name %>
      </option>
      <% end %>
    </select><br>
    <label>Start Date:
        <input name="cat_rental_request[start_date]" type="date">
    </label><br>
    <label>End Date:
      <input name="cat_rental_request[end_date]" type="date">
  </label><br>
  <input type="submit">
</form>

CatsCatsCats/app/views/cat_rental_requests/index.html.erb
<%= link_to "Request a Cat", new_cat_rental_request_url%>

<%= link_to "All of the Cats", cats_url%>

CatsCatsCats/app/views/cat_rental_requests/new.html.erb
<h1> Apply For Feline Friend</h1>
<%= render 'form' %>
<br><br>


<%= link_to "Back to the Cats", cats_url %>

CatsCatsCats/app/views/cats/_form.html.erb
<% action_url = @cat.persisted? ? cat_url(@cat) : cats_url %>
<% method = @cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = @cat.persisted? ? "Update Cat!" : "Create Cat!" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= method %>">
  <label>Name:
      <input name="cat[name]" type="text" value="<%= @cat.name %>">
  </label>
  <br>
  <label>Birth:
      <input name="cat[birth]" type="date" value="<%= @cat.birth %>">
  </label>
    <br>
  <label>Color:
    <select name="cat[color]">
      <option> <!-- blank option -->
      </option>
      <option 
        value="white" 
        selected="<%'selected' if @cat.color = 'white'%>">
        White
      </option>
      <option 
        value="black" 
        selected="<%'selected' if @cat.color = 'black'%>">
        Black
      </option>
      <option 
        value="green" 
        selected="<%'selected' if @cat.color = 'green'%>">
        Green
      </option>
      <option 
        value="gray" 
        selected="<%'selected' if @cat.color = 'gray'%>">
        Gray
      </option>
    </select>
  </label>
    <br>
    <label>Sex:<br>
      <input 
        name="cat[sex]" 
        type="radio" 
        value="M" 
        <%= 'checked' if @cat.sex == 'M'%>> Male <br>
      </label>
      
      <label>
      <input 
        name="cat[sex]" 
        type="radio" 
        value="F" 
        <%= 'checked' if @cat.sex == 'F'%>> Female <br>
      </label>
    <br>
    <label>Description:<br>
      <textarea 
        name="cat[description]"
        ><%= @cat.description %></textarea><br>
    </label>
    <input type="submit" value="<%=submit_text%>">
</form>

<%= link_to "All of the cats", cats_url %>

CatsCatsCats/app/views/cats/edit.html.erb
<h1> Update!</h1>
<form action="<%= cat_url(@cat)%>" method="post">
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">
  <label>Name:
      <input name="cat[name]" type="text" value="<%= @cat.name %>">
  </label>
  <br>
  <label>Birth:
      <input name="cat[birth]" type="date" value="<%= @cat.birth %>">
  </label>
    <br>
  <label>Color:
    <select name="cat[color]">
      <option> <!-- blank option -->
      </option>
      <option value="white", selected="<%'selected' if @cat.color = 'white'%>">
        White
      </option>
      <option value="black", selected="<%'selected' if @cat.color = 'black'%>">
        Black
      </option>
      <option value="green", selected="<%'selected' if @cat.color = 'green'%>">
        Green
      </option>
      <option value="gray", selected="<%'selected' if @cat.color = 'gray'%>">
        Gray
      </option>
    </select>
  </label>
    <br>
    <label>Sex:<br>
      <input name="cat[sex]" type="radio" value="M" <%= 'checked' if @cat.sex == 'M'%>> Male <br>
      <input name="cat[sex]" type="radio" value="F" <%= 'checked' if @cat.sex == 'F'%>> Female <br>
    </label>
    <br>
    <label>Description:<br>
        <textarea name="cat[description]"><%= @cat.description %>
        </textarea><br>
    </label>
    <input type="submit">
</form>

<%= link_to "All of the cats", cats_url %>

CatsCatsCats/app/views/cats/index.html.erb
<div id="entire_show">
<table>
  <th> Name </th>
  <th> Sex </th>
  <th> Color </th>
  <th> Description </th> 
  <th> Birth </th>
   <% @cats.each do |cat| %>
  <tr>
    <td> <%= link_to cat.name, cat_url(cat)%></td>
    <td><%= cat.sex%></td>
    <td><%= cat.color%></td>
    <td><%= cat.description%></td>
    <td><%= cat.birth%></td>
  </tr>
  <% end %>
</table><br>
<%= link_to "Create a Cat!", new_cat_url %><br>
<%= link_to "Request a Cat", new_cat_rental_request_url%>
</div>

CatsCatsCats/app/views/cats/new.html.erb
<h1> Create a Cat!</h1>
<%= flash[:errors] && flash[:errors].to_json%>

<%= render 'form' %>

CatsCatsCats/app/views/cats/show.html.erb
<div id="entire_show">
<h3> <%= @cat.name %>!</h3>
<table>
  <th> Name </th>
  <th> Sex </th>
  <th> Color </th>
  <th> Description </th> 
  <th> Birth </th>
  <tr>
    <td> <%= @cat.name %></td>
    <td><%= @cat.sex%></td>
    <td><%= @cat.color%></td>
    <td><%= @cat.description%></td>
    <td><%= @cat.birth%></td>
  </tr>
</table>



<%= link_to "Edit Cat", edit_cat_url(@cat)%>
<%= link_to "All of the Cats", cats_url%> 

<br>
<br>
<div id="show_wrapper">
<h4> <%= @cat.name %>'s Rental Requests</h4>
<% if @requests.each do |request|%>
<ul>
  <li>
    Requester: <%= User.find(request.user_id).user_name %>
  </li>
  <li> 
    Start Date: <%= request.start_date%>
  </li>
  <li> 
    End Date: <%= request.end_date%>
  </li>
  <li> 
    Status: <%= request.status%>
  </li>
</ul>
  <% if current_user.id == @cat.user_id %>
  <ul id="show_list">
  <div id="show_div"><li><%= button_to "Approve", approve_cat_rental_request_url(request.id) %>
  </li>
  <li> <%= button_to "Deny", deny_cat_rental_request_url(request.id) %>
  </li>
  </div>
  </ul>
  </div>
  <% end %>
<%end%>
<%end%>
</div>

CatsCatsCats/app/views/layouts/_errors.html.erb
<% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
   <%= error %><br />
  <% end %>
<% end %>

CatsCatsCats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CatsCatsCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="jumbotron top">
    <% if !current_user.nil? %>
    <h1>Welcome <%= current_user.user_name.capitalize %>!</h1>
    <%= button_to "Logout", delete_session_url, method: :delete, class: "btn btn-default log"%> <br>
    <%else%>
    <h1>Welcome!</h1>
    <div id="hide_log_in">
    <%= link_to "Log in", new_session_url%>
      <%end%>
    </div>
      </div>
    <%= yield %>
</div>
</body>
</html>

CatsCatsCats/app/views/users/_form.html.erb
<form action="/users" method="POST">
  <input 
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
    
 <label>Username:
    <input 
      name="user[user_name]" 
      type="text">
 </label><br>
 
 <label>Password:
     <input name="user[password]" type="password">
 </label><br>
  <input type="submit">
</form>

CatsCatsCats/app/views/users/new.html.erb
<div class="login_wrapper">
<h1> Create Account!</h1>
<%= render 'form' %>
</div>